In [1]:
# Importar a lib
import numpy as np

In [2]:
# Versão
print(np.__version__)

1.26.4


In [4]:
# Criar uma matriz
Array = np.array( [10,20,30,40,50] )

Array

array([10, 20, 30, 40, 50])

In [7]:
# Tipo
type( Array )

numpy.ndarray

In [8]:
Duas = np.array(
    [[10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]]
)

print(Duas)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [9]:
Tres = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

print( Tres )

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [19]:
# Experimento de Processamento
Estressando_NP = np.arange( 1000000 )
Estressando_NP_02 = np.arange( 5000000 )
Estressando_NP_03 = np.arange( 10000000 )
Estressando_NP_04 = np.arange( 50000000 ) # excel 3mm

print(len(Estressando_NP), len(Estressando_NP_02), len(Estressando_NP_03), len(Estressando_NP_04) )

1000000 5000000 10000000 50000000


In [16]:
# 1º Teste
%time for Loop in Estressando_NP: pass

CPU times: total: 109 ms
Wall time: 107 ms


In [20]:
# 2º Teste
%time for Loop in Estressando_NP_02: pass

CPU times: total: 547 ms
Wall time: 544 ms


In [21]:
# 3º Teste
%time for Loop in Estressando_NP_03: pass

CPU times: total: 1.06 s
Wall time: 1.06 s


In [22]:
# 4º Teste
%time for Loop in Estressando_NP_04: pass

CPU times: total: 5.16 s
Wall time: 5.14 s


In [25]:
# Acessar os arrays
# 1º Posição
Array[0]

10

In [26]:
# Ultima
Array[-1]

50

In [27]:
# Range
Array[2:]

array([30, 40, 50])

In [29]:
# Operações
print(Array[0], Array[1])
Array[0] + Array[1]

10 20


30

In [30]:
Array[0] - Array[1]

-10

In [31]:
Array[0] * Array[1]

200

In [32]:
Array[0] / Array[1]

0.5

In [33]:
# Operadores Logicos
Array[0] == Array[1]

False

In [34]:
Array[0] >= Array[1]

False

In [35]:
Array[0] <= Array[1]

True

In [36]:
Array[0] != Array[1]

True

In [37]:
# Verificar Dimensão
Array.shape

(5,)

In [38]:
Duas.shape

(2, 5)

In [39]:
Tres.shape

(3, 5)

In [41]:
# Loop
for Loop in Array:
    print(Loop)

10
20
30
40
50


In [44]:
for Loop in Duas:
    for Interno in Loop:
        print(Interno)

10
9
8
7
6
5
4
3
2
1


In [46]:
for Loop in Tres:
    for Interno in Loop:
        print(Interno)

15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [47]:
import pandas as pd


In [50]:
pd.DataFrame( Array, columns=['Vetor 1 Dimensao'])

Vetor 1 Dimensao
0                10
1                20
2                30
3                40
4                50